# Generated by Django 6.0.6 on 2026-06-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_addresses', models.TextField()),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('received_date', models.DateTimeField()),
                ('raw_email', models.FileField(blank=True, upload_to='emails/')),
                ('linked_to_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='ImapAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=993)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(help_text='Encrypted at rest', max_length=200)),
                ('use_ssl', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='attachments/')),
                ('parsed_text', models.TextField(blank=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contacts.communication')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('LICENSE_HOLDER', 'License Holder')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('opt_in', models.BooleanField(default=False)),
                ('opt_in_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='imap_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='contacts.imapaccount'),
        ),
    ]
