# Generated by Django 6.0.6 on 2026-06-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(help_text='e.g. Sparx EA Corporate, Sparx EA Professional', max_length=200)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField(help_text='Typically end of month')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='contacts.customer')),
                ('source_attachment', models.ForeignKey(blank=True, help_text='PDF/TXT document this license info was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='contacts.attachment')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LicenseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('is_service', models.BooleanField(default=False, help_text='Rented on 12-month basis')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='contacts.license')),
            ],
        ),
    ]
