# Generated by Django 6.0.6 on 2026-06-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_license_licenselineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='renewed_license',
            field=models.ForeignKey(blank=True, help_text='Previous license this is a renewal of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='contacts.license'),
        ),
        migrations.AlterField(
            model_name='licenselineitem',
            name='description',
            field=models.CharField(help_text='Product or service name', max_length=500),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('quote_file', models.CharField(blank=True, help_text='Path to quote PDF on OneDrive (e.g. OneDrive/EAxpertise/Quotes/...)', max_length=500, verbose_name='quote (PDF)')),
                ('invoice_file', models.CharField(blank=True, help_text='Path to invoice PDF on OneDrive (e.g. OneDrive/EAxpertise/Invoices/...)', max_length=500, verbose_name='invoice (PDF)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='contacts.customer')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddField(
            model_name='license',
            name='purchase',
            field=models.ForeignKey(blank=True, help_text='Purchase that originated this license', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='contacts.purchase'),
        ),
    ]
