# Generated by Django 6.0.6 on 2026-06-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_license_renewed_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expiry_month',
            field=models.DateField(blank=True, help_text='Service expiry (set to last day of month) — signals renewal needed', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='service_name',
            field=models.CharField(blank=True, help_text='Name of the service (for Service-type purchases)', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='start_month',
            field=models.DateField(blank=True, help_text='Service start (set to 1st of month)', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], default='PRODUCT', max_length=10),
        ),
    ]
