# Generated by Django 6.0.6 on 2026-06-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_purchase_expiry_month_purchase_service_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, upload_to='invoices/')),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, upload_to='quotes/')),
                ('seen', models.BooleanField(default=False, help_text='Quote has been reviewed')),
                ('order_placed', models.BooleanField(default=False, help_text='Quote approved and order placed')),
                ('cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quote_file',
        ),
        migrations.AddField(
            model_name='license',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice that procured this license', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='contacts.invoice'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Invoice that fulfilled this procurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='contacts.invoice'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quote',
            field=models.OneToOneField(blank=True, help_text='Quote that triggered this procurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='contacts.quote'),
        ),
    ]
