# Generated by Django 6.0.6 on 2026-06-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='EAxNewsletter', max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField(blank=True, help_text='HTML version of newsletter')),
                ('body_text', models.TextField(blank=True, help_text='Plain text version')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('SENT', 'Sent')], default='DRAFT', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'news source',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(unique=True)),
                ('heading', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('included', models.BooleanField(default=False)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsletter.newsletter')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsletter.newssource')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('opened_date', models.DateTimeField(blank=True, null=True)),
                ('bounced', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_sendouts', to='contacts.contact')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendouts', to='newsletter.newsletter')),
            ],
            options={
                'verbose_name': 'newsletter contact',
                'verbose_name_plural': 'newsletter contacts',
                'unique_together': {('newsletter', 'contact')},
            },
        ),
    ]
